### ISSUE TITLE
startup problem and display issue on high resolution video

### ISSUE THREAD

**Issue by lallous34** [econsysqtcam/qtcam#23]
when using QTCam I am facing 2 issues:

1- the program startup takes a long time. also i have the following warning :
libpng warning: iCCP: known incorrect sRGB profile

second issue, when using ECON C80, C130 cameras or a logitech camera and i go to a high resolution (1920x1080 and higher) the camera display begin to lag and "framed" (frames are not continuous). even when i use mjpeg on high fps (30) 

i am building the code on QT 5.9.2

**Comment by econsysqtcam** [comment]
Please find my reply inline.

**1- the program startup takes a long time.**
This issue has fixed in recent release. Please update and use the latest Qtcam version 16.0.6.

**also i have the following warning :
libpng warning: iCCP: known incorrect sRGB profile**
I suspect Qt version. We are using Qt5.2.1.  We are not facing this warning.

**second issue, when using ECON C80, C130 cameras or a logitech camera and i go to a high resolution (1920x1080 and higher) the camera display begin to lag and "framed" (frames are not continuous). even when i use mjpeg on high fps (30)**
Please create support ticket using the link https://www.e-consystems.com/create-ticket.asp
